export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const GET_STUDENT_ANALYTICS_SUCCESS = "GET_STUDENT_ANALYTICS_SUCCESS";
export const GET_STUDENT_ANALYTICS_LOADING = "GET_STUDENT_ANALYTICS_LOADING";
export const GET_STUDENT_ANALYTICS_FAILED = "GET_STUDENT_ANALYTICS_FAILED";
