// Authentication
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// Permissions
export const ADD_PERMISSION = "ADD_PERMISSION";
export const DELETE_PERMISSION = "DELETE_PERMISSION";
export const GET_PERMISSIONS = "GET_PERMISSIONS";
export const ADD_PERMISSIONGROUP = "ADD_PERMISSIONGROUP";
export const DELETE_PERMISSIONGROUP = "DELETE_PERMISSIONGROUP";
export const GET_PERMISSIONGROUPS = "GET_PERMISSIONGROUPS";
