//
export const GET_ASSIGNMENTS_SUCCESS = "GET_ASSIGNMENTS_SUCCESS";
export const GET_ASSIGNMENTS_LOADING = "GET_ASSIGNMENTS_LOADING";
export const GET_ASSIGNMENTS_FAILED = "GET_ASSIGNMENTS_FAILED";
//
export const ADD_ASSIGNMENT_SUCCESS = "ADD_ASSIGNMENT_SUCCESS";
export const ADD_ASSIGNMENT_LOADING = "ADD_ASSIGNMENT_LOADING";
export const ADD_ASSIGNMENT_FAILED = "ADD_ASSIGNMENT_FAILED";
//
