//
export const GET_ASSIGNMENTS_SUCCESS = "GET_ASSIGNMENTS_SUCCESS";
export const GET_ASSIGNMENTS_LOADING = "GET_ASSIGNMENTS_LOADING";
export const GET_ASSIGNMENTS_FAILED = "GET_ASSIGNMENTS_FAILED";
//
export const ADD_ASSIGNMENT_SUCCESS = "ADD_ASSIGNMENT_SUCCESS";
export const ADD_ASSIGNMENT_LOADING = "ADD_ASSIGNMENT_LOADING";
export const ADD_ASSIGNMENT_FAILED = "ADD_ASSIGNMENT_FAILED";
//
//
//
export const GET_ALL_ASSIGNMENT_FILES_SUCCESS =
  "GET_ALL_ASSIGNMENT_FILES_SUCCESS";
export const GET_ALL_ASSIGNMENT_FILES_LOADING =
  "GET_ALL_ASSIGNMENT_FILES_LOADING";
export const GET_ALL_ASSIGNMENT_FILES_FAILED =
  "GET_ALL_ASSIGNMENT_FILES_FAILED";
//
export const GET_ASSIGNMENT_FILE_SUCCESS = "GET_ASSIGNMENT_FILE_SUCCESS";
export const GET_ASSIGNMENT_FILE_LOADING = "GET_ASSIGNMENT_FILE_LOADING";
export const GET_ASSIGNMENT_FILE_FAILED = "GET_ASSIGNMENT_FILE_FAILED";
//
export const ADD_ASSIGNMENT_FILE_SUCCESS = "ADD_ASSIGNMENT_FILE_SUCCESS";
export const ADD_ASSIGNMENT_FILE_LOADING = "ADD_ASSIGNMENT_FILE_LOADING";
export const ADD_ASSIGNMENT_FILE_FAILED = "ADD_ASSIGNMENT_FILE_FAILED";
