export const GET_EXAMS_SUCCESS = "GET_EXAMS_SUCCESS";
export const GET_EXAMS_LOADING = "GET_EXAMS_LOADING";
export const GET_EXAMS_FAILED = "GET_EXAMS_FAILED";
//
export const GET_EXAMRESULTS_ALL_SUCCESS = "GET_EXAMRESULTS_ALL_SUCCESS";
export const GET_EXAMRESULTS_ALL_LOADING = "GET_EXAMRESULTS_ALL_LOADING";
export const GET_EXAMRESULTS_ALL_FAILED = "GET_EXAMRESULTS_ALL_FAILED";
//
export const GET_EXAMRESULTS_PERSTUDENT_SUCCESS =
    "GET_EXAMRESULTS_PERSTUDENT_SUCCESS";
export const GET_EXAMRESULTS_PERSTUDENT_LOADING =
    "GET_EXAMRESULTS_PERSTUDENT_LOADING";
export const GET_EXAMRESULTS_PERSTUDENT_FAILED =
    "GET_EXAMRESULTS_PERSTUDENT_FAILED";
//
export const GET_EXAMRESULTS_PERCLASS_PERSUBJECT_SUCCESS =
    "GET_EXAMRESULTS_PERCLASS_PERSUBJECT_SUCCESS";
export const GET_EXAMRESULTS_PERCLASS_PERSUBJECT_LOADING =
    "GET_EXAMRESULTS_PERCLASS_PERSUBJECT_LOADING";
export const GET_EXAMRESULTS_PERCLASS_PERSUBJECT_FAILED =
    "GET_EXAMRESULTS_PERCLASS_PERSUBJECT_FAILED";
//
export const ADD_EXAMRESULTS_PER_STUDENT_SUCCESS =
    "ADD_EXAMRESULTS_PER_STUDENT_SUCCESS";
export const ADD_EXAMRESULTS_PER_STUDENT_LOADING =
    "ADD_EXAMRESULTS_PER_STUDENT_LOADING";
export const ADD_EXAMRESULTS_PER_STUDENT_FAILED =
    "ADD_EXAMRESULTS_PER_STUDENT_FAILED";
//
export const ADD_EXAMRESULTS_PER_CLASS_SUCCESS =
    "ADD_EXAMRESULTS_PER_CLASS_SUCCESS";
export const ADD_EXAMRESULTS_PER_CLASS_LOADING =
    "ADD_EXAMRESULTS_PER_CLASS_LOADING";
export const ADD_EXAMRESULTS_PER_CLASS_FAILED =
    "ADD_EXAMRESULTS_PER_CLASS_FAILED";
