export const GET_STREAMS = "GET_STREAMS";
export const ADD_STREAM = "ADD_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";
export const GET_CLASSNUMERALS = "GET_CLASSNUMERALS";
export const ADD_CLASSNUMERAL = "ADD_CLASSNUMERAL";
export const DELETE_CLASSNUMERAL = "DELETE_CLASSNUMERAL";
