export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_LOADING = "GET_STUDENTS_LOADING";
export const GET_STUDENTS_FAILED = "GET_STUDENTS_FAILED";
// cache
export const INVALIDATE_STUDENT_CACHE = "INVALIDATE_STUDENT_CACHE";
export const VALIDATE_STUDENT_CACHE = "VALIDATE_STUDENT_CACHE";
