export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_FAILED = "GET_SUBJECTS_FAILED";
export const GET_SUBJECTS_LOADING = "GET_SUBJECTS_LOADING";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
