name: Build and Deploy
on:
  push:
    branches:
      - deploy
      - master
  pull_request:
    branches:
      - deploy

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: ShuleSuite/core
          token: ${{ secrets.MY_PAT }}
          path: my-tools
        
      - name: Content list
        working-directory: ${{ github.workspace }}  
        run: ls -la 
        
      - name: Content list
        working-directory: main 
        run: ls -la 
      - name: Content list
        working-directory: my-tools
        run: ls -la 
      - name: Install Requirements
        working-directory: my-tools
        run: echo $PATH
        

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        working-directory: my-tools
        run: pip install -r requirements.txt
      - name: Install Dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Build
        env:
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
        run: yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
