name: Build and Deploy
on:
  push:
    branches:
      - deploy
      - master
  pull_request:
    branches:
      - deploy

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Checkout Backend
        uses: actions/checkout@master
        with:
          name: ShuleSuite/core
      - name: Install Dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Build
        env:
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
        run: yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
