name: Build and Deploy
on:
  push:
    branches:
      - deploy
      - master
  pull_request:
    branches:
      - deploy

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend
        run: git clone"https://${{ secrets.my_pat }}@github.com/ShuleSuite/core.git" /other-private-repo

      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Content list
        uses: enricomarino/actions@v2
        with:
          source: my-tools
      - name: Install Requirements
        run: echo $PATH
      - name: Install Requirements
        run: ls
      - name: Install Requirements
        working-directory: my-tools
        run: echo $PATH
        

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        working-directory: my-tools
        run: pip install -r requirements.txt
      - name: Install Dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Build
        env:
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
        run: yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
