name: Build and Deploy
on:
  push:
    branches:
      - deploy
      - master
  pull_request:
    branches:
      - deploy

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: ShuleSuite/core
          token: ${{ secrets.MY_PAT }}
          path: backend  

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        working-directory: backend
        run: |
          pip install -r requirements.txt
          python manage.py runserver
      - name: Install Dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Build
        env:
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
        run: yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
